export type ShadowRunStatus = 'ACTIVE' | 'COMPLETED' | 'ABORTED';
export type GoNoGoStatus = 'GO' | 'NO_GO' | 'NOT_RUN';
export type SafeShadowEvent = 'SHADOW_MODE_BLOCKED' | 'SHADOW_RUN_STARTED' | 'SHADOW_RUN_FINISHED' | 'SHADOW_RUN_ABORTED';
export interface ShadowLogger { info(event: string, metadata: Record<string, string | number | boolean>): void; }
export interface ShadowCounts { totalCollected: number; totalQualified: number; totalRejected: number; totalDuplicates: number; totalBlocked: number; totalOptOut: number; totalWithoutWebsite: number; totalInadequatePresence: number; totalValidContacts: number; totalProbableWhatsapp: number; totalConfirmedWhatsapp: number; totalHighScore: number; totalMediumScore: number; totalLowScore: number; falsePositiveSampleCount: number | null; humanReviewSampleCount: number | null; }
export interface ShadowRun extends ShadowCounts { runId: string; startedAt: string; finishedAt: string | null; segment: string; region: string; source: string; status: ShadowRunStatus; incidents: string[]; warnings: string[]; evidenceIds: string[]; generatedAt: string | null; abortReason: string | null; }
const zero = (): ShadowCounts => ({ totalCollected: 0, totalQualified: 0, totalRejected: 0, totalDuplicates: 0, totalBlocked: 0, totalOptOut: 0, totalWithoutWebsite: 0, totalInadequatePresence: 0, totalValidContacts: 0, totalProbableWhatsapp: 0, totalConfirmedWhatsapp: 0, totalHighScore: 0, totalMediumScore: 0, totalLowScore: 0, falsePositiveSampleCount: null, humanReviewSampleCount: null });
export class ShadowModeGuard {
  blockedCount = 0;
  constructor(readonly enabled: boolean, private readonly logger: ShadowLogger) {}
  block(runId = 'unscoped'): boolean { if (!this.enabled) return false; this.blockedCount++; this.logger.info('shadow_mode_outbound_blocked', { event: 'SHADOW_MODE_BLOCKED', outcome: 'BLOCKED', reason: 'SHADOW_MODE_BLOCKED', runId, durationMs: 0 }); return true; }
}
export class ShadowRunStore {
  private readonly runs = new Map<string, ShadowRun>();
  start(input: { runId: string; segment: string; region: string; source: string; now: Date }): ShadowRun { const prior = this.runs.get(input.runId); if (prior) return prior; const run: ShadowRun = { runId: input.runId, segment: input.segment, region: input.region, source: input.source, startedAt: input.now.toISOString(), finishedAt: null, status: 'ACTIVE', incidents: [], warnings: [], evidenceIds: [], generatedAt: null, abortReason: null, ...zero() }; this.runs.set(run.runId, run); return run; }
  get(runId: string) { return this.runs.get(runId); }
  addEvidence(runId: string, evidenceId: string, counts: Partial<ShadowCounts>) { const run = this.require(runId); if (run.evidenceIds.includes(evidenceId)) return run; if (run.status !== 'ACTIVE') throw new Error('SHADOW_RUN_NOT_ACTIVE'); run.evidenceIds.push(evidenceId); for (const [key, value] of Object.entries(counts)) if (typeof value === 'number') { const target = run as unknown as Record<string, number>; target[key] = (target[key] ?? 0) + value; } return run; }
  finish(runId: string, now: Date) { const run = this.require(runId); if (run.status === 'ACTIVE') { run.status = 'COMPLETED'; run.finishedAt = now.toISOString(); } return run; }
  abort(runId: string, reason: 'OPERATOR_ABORT' | 'SAFETY_ABORT', now: Date) { const run = this.require(runId); if (run.status === 'ACTIVE') { run.status = 'ABORTED'; run.abortReason = reason; run.finishedAt = now.toISOString(); } return run; }
  private require(id: string) { const run = this.runs.get(id); if (!run) throw new Error('SHADOW_RUN_NOT_FOUND'); return run; }
}
export function evaluateShadowGoNoGo(run: ShadowRun, input: { guardBlocked: number; criticalIncident: boolean; readiness: boolean; backup: boolean; rollback: boolean; reportGenerated: boolean; maxDuplicateRate?: number; minQualifiedPrecision?: number; qualificationPrecision?: number | null; falsePositiveRate?: number | null }): { status: GoNoGoStatus; criteria: Record<string, 'PASS' | 'FAIL' | 'NOT_RUN'> } { const duplicateRate = run.totalCollected ? run.totalDuplicates / run.totalCollected : null; const criteria = { noOutbound: input.guardBlocked > 0 ? 'PASS' : 'NOT_RUN', duplicates: duplicateRate === null ? 'NOT_RUN' : duplicateRate <= (input.maxDuplicateRate ?? .05) ? 'PASS' : 'FAIL', precision: input.qualificationPrecision == null ? 'NOT_RUN' : input.qualificationPrecision >= (input.minQualifiedPrecision ?? .85) ? 'PASS' : 'FAIL', falsePositive: input.falsePositiveRate == null ? 'NOT_RUN' : input.falsePositiveRate <= .15 ? 'PASS' : 'FAIL', readiness: input.readiness ? 'PASS' : 'FAIL', backup: input.backup ? 'PASS' : 'FAIL', rollback: input.rollback ? 'PASS' : 'FAIL', report: input.reportGenerated ? 'PASS' : 'FAIL' } as const; return { status: input.criticalIncident || Object.values(criteria).some((v) => v !== 'PASS') ? 'NO_GO' : 'GO', criteria }; }
export function createShadowReport(run: ShadowRun, goNoGo: ReturnType<typeof evaluateShadowGoNoGo>, input: { backlog: number; deadLetters: number; retries: number; guardBlocked: number; now: Date }) { return { schemaVersion: '1.0', containsPii: false, period: { startUtc: run.startedAt, endUtc: run.finishedAt }, scope: { segment: run.segment, region: run.region, source: run.source }, readiness: { phase: 'SHADOW_MODE', percentage: goNoGo.status === 'GO' ? 100 : 0, decision: goNoGo.status, criteria: goNoGo.criteria }, volume: run, operational: { backlog: input.backlog, deadLetters: input.deadLetters, retries: input.retries, shadowModeBlocked: input.guardBlocked }, commercialFunnel: { contacted: 'NOT_RUN', responses: 'NOT_RUN', meetings: 'NOT_RUN', proposals: 'NOT_RUN', sales: 'NOT_RUN' }, generatedAt: input.now.toISOString() }; }
